sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
install:
  - npm install webpack -g
  - pwd
  - cd ../
  - git clone -b "2.4.0" https://github.com/Graylog2/graylog2-server.git
  - cd graylog2-server/graylog2-web-interface
  - npm install
  - webpack --config webpack.vendor.js
  - pwd
  - cd ../../graylog-plugin-quickvaluesplus-widget
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
addons:
  apt:
    packages:
      - rpm
before_deploy:
- mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
- mvn rpm:rpm && export RELEASE_RPM_FILE=$(find target/ -name '*.rpm' | tail -1)
- rm -f target/original-*.jar
- export RELEASE_PKG_FILE=$(ls target/*.jar)
- echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: e1lIcnvHdc3suR294QbSBKKH4bUewTZztslx1zA0wofFJwcYg76yrcbUIbrC6ZsrxVovVIJaeMIkgwYhaUfZaipq3/jolx8V3acYYUPNfoglamxWBinCoO85SmXQWnLjgEgt5B+HaRz/TK3BBhAifq5/jSwqUbmegkDnYLIxQ5BsRKKYIXeHQ55Mv+QEhofNSpexCS4t1OUByFPihUIyWcdsUvmMQ6SELiWW7ootFHexifU8usJ58BUSmmHmuItLxdF7CV8qA1HAc/sgroN+JHHznpSusfRb7eyO3RykqoAByYhk/K/cp5TtQwRzlBJCnMVkcsuDIYSjgQFFrHh4vg24sfq4fuxhLthYI6Lsff9/JhRf8kpNeSwV1UrkEf9BY3qtYsRI4VFCn9bvfloRxd+zos4PBkRPKYDWS/aKHplM2ElbVdRkiU5AvA3vcbupSbfYlznEfY2fZ7ehaWA3Y3ZvvmAAAUD0zU9aOg8EoKSdYdPiTPLYNCZnm5Mj3Ly6H56axW7jPmkhjt7dODLqcG2O/6QF+JncTd6o+QoGlF658jvfShwbxRKu3840NkofT7o0X6uZN9vZmzsFmOYwKcmItjyg/Yte0bXM4poklYMF+EmRD1yQoSvewXNylqM92zCHWCSqbJpeeEyNIRQwTXm+nICXbp0NxVcEU9FxAXM=
  file_glob: true
  file:
    - "${RELEASE_PKG_FILE}"
    - "${RELEASE_DEB_FILE}"
    - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    repo: billmurrin/graylog-plugin-quickvaluesplus-widget
    tags: true
    jdk: oraclejdk8